version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      # Prefix all commit messages
      prefix: "[Dependabot] npm"
    labels:
      # Add these labels to the Generated PR
      - "npm"
      - "dependencies"
      - "update"
    allow:
      # Allow specific libraries to be updated
      # By default, it would check everything, even in the lock
      - "react*"
      - "redux*"
      - 
    